export const defaultTheme = {
    colors: {
        "base-white": "#ffffff",
        "base-background-card": "#d7fff1",
        "base-background-card2": "#e4e4eb",
        "base-background-card3": "#f0f0f5",
        "base-background-overlay": "#000000",
        "base-background": "#8D8686",
        "base-background-light": "#e3d3e4",
        "base-background-light2": "#eceaea",
        "base-text": "#333333",
        "base-red": "#c72828",
        "base-red-light": "#db5375",
        "base-green-light": "#41c900",
        "base-green-dark": "#39b100",
        "base-orange": "#ffb84d",
        "base-gray": "#3d3d4d",
        "base-input-checked": "#2196f3",
        "base-modal-background": "#fff",
        "base-modal-input": "#b7b7cc",
        'base-span': '#7B96B2',
        'base-border': '#1C2F41',
        'base-input': '#040F1A',
        'base-text2': '#AFC2D4',
        'base-blue': '#253d5b',
        'base-blue-light': '#a1c6ea',
        'base-purple-dark': '#52489c',
        'base-subtitle': '#C4D4E3',
        'base-label': '#3A536B',
    },
    fonts: {
        "base-font": "Poppins, sans-serif",
    },
    textSizes: {
        'title-title-m': '1rem',
        'title-title-l': '1.5rem',
        'title-title-s': '1.125rem',
        'text-text-s': '0.875rem',
        'text-text-m': '1rem',
        'components/link': '0.75rem',
    },
    fontWeights: {
        "base-font-weight": "600",
    }
};